### ISSUE TITLE
'blender.exe.' from zip downloaded from github isn't executatble

### ISSUE THREAD

**Issue by blastfurnace360** [anaseinea/Blendity#2]
Hey Annas, this package is great - enormous potential here. I wanted to mention to you that there a few snags using this - 
1 - when I download the package from git, for some reason the 'blender.exe' file in the 'blender~' directory can't be run - on my machine it says 'this app can't be run on your pc' like it's corrupted or something - maybe it's a git encoding issue. I also got this through itch.io and that one works fine when I install the package from disk
2 - provided 'blender.exe' is executable, when I 'generate spaceship', I can see that the resulting fbx file has the 'Light', 'Camera' and 'Block' which are parts of the default Blender scene when you open it. The 'fracture.py' file has an error because of this - it messes up because line 15 is trying to execute ps = obj.modifiers.new("Part", 'PARTICLE_SYSTEM').particle_system on the 'Light'. If I put a conditional on line 15

if (obj.name != 'Light') and (obj.name != 'Camera'):

and put the following lines in the conditional, it completes successfully but again, the Block from the default scene is included in the generated model.

Not sure what is causing #1 but it might also do that when importing from git url. For #2 I think you just have to empty the scene and save it as the startup.blend file included in the 'blender~' directory.

**Comment by blastfurnace360** [comment]
I think Blender might be doing something sneaky where it's actually keeping the startup file in some User directory. In any case - on my machine apparently it still had the Light, Camera, and Block which caused both parts of #2 - might be easiest to actually clear the scene before importing the model being generated or modified.

Also you might already know of this, but Unity 2020.3 can't open the Blendity.ParamsModal, it's just a white box. Only after installing 2019.4 (like it says in the readme) was I able to use it.

**Comment by anaseinea** [comment]
Thank you so much for reporting, not really sure about #1 will have to test further
#2 I was foolish to think that startup settings are saved within blender folder, I already added checks for type of object in next release so that if the original file has lights or empty objects it wont fail.

Edit: turns out you just need to create a "Config" folder within "blender~/2.92" and it will save prefs in it

**Comment by blastfurnace360** [comment]
Anas, that's great! I changed the title of this issue so it highlights the remaining issue better. I did a test where I downloaded the zip from github and did a 'git clone' - the downloaded zip from github had the non-executable blender.exe in it and the git cloned one was fine.
This issue where 'blender.exe' isn't able to run must just be isolated to downloading the zip from github.

**Comment by blastfurnace360** [comment]
Actually as I'm looking closer, the downloaded zip has a 'blender.exe' file that's only 1kb and the cloned one is 164mb (I do have git lfs installed). I'm pretty sure this is just showing the difference between git without 'large file storage' and with - because the downloaded zip I don't think has the 'large file support'.
You may just need to change the readme and highlight that downloading the zip from github isn't an option because of the 100mb file size limit that's applied without 'large file support'.
In addition, you might want to consider more verbose logging in Unity if the blender.exe file is not executable - I could see the python error in the console which was a good clue but this would also happen to someone who doesn't have git lfs installed. You might add some sort of check on the filesize of 'blender.exe' and log something about the repo not being cloned right to help the user?

**Comment by anaseinea** [comment]
oh that makes sense !
thank you for investigating I really appreciate it
will update the README and push new features soon

**Comment by anaseinea** [comment]
@blastfurnace360 changes are in. please test when you can and close the issue accordingly

**Comment by blastfurnace360** [comment]
perfect! No more 'Light', 'Camera', and 'Block' from the default scene. If you open blender from the 'blender~' folder and change the default scene from there you again start getting the objects from there with your generated/modified model, but it's pretty unlikely anybody would do that. Now getting things to work immediately is much simpler.

**Comment by anaseinea** [comment]
Hey thank you for your detailed email,
Issue 1 is because I am using git lfs and so when you download from git it
doesn't download the exe files which are in git lfs
You can clone the repo if you want but you have to have git lfs installed

Issue 2 feels like you don't have the new version of the package or that
your local default file is messing with the default file shipped in my
package
